// <<<LLMCTX
// FILE: crates/core/src/process.rs
// ROLE: Keystone decision function — extract comment block or fall back to Ollama, then write the context store
// EXPORTS: process_file(), stored_context(), stored_hash(), content_hash(), ProcessResult, ProcessSource, ProcessError
// IMPORTS: crates/core/src/store.rs, crates/core/src/config.rs, crates/core/src/extract.rs, crates/core/src/ollama.rs
// USED BY: crates/daemon/src/main.rs, crates/cli/src/main.rs
// NOTES: Daemon and CLI must call this function — never reimplement the branch logic themselves
// LLMCTX>>>

use std::path::Path;

use sha2::{Digest, Sha256};
use thiserror::Error;
use tracing::{debug, info, warn};

use crate::{
    config::{self, ProjectConfig},
    extract::{self, ExtractError},
    ollama::{OllamaClient, OllamaError},
    store::{ContextStore, Lookup, StoreError},
};

// ── Public types ─────────────────────────────────────────────────────────────

/// Which code path produced the stored context.
#[derive(Debug, Clone, PartialEq, Eq)]
pub enum ProcessSource {
    /// Context came from an `<<<LLMCTX` comment block in the file itself.
    Extracted,
    /// Context was generated by Ollama.
    Ollama,
    /// The store already holds context for this exact file content — nothing to do.
    UpToDate,
    /// Context was carried over from another path with identical content
    /// (the file was renamed, moved or copied).
    Reused,
    /// File was too small to bother Ollama (< MIN_LINES lines).
    SkippedTooSmall,
    /// File was too large to be worth sending to a small local model.
    SkippedTooLarge,
    /// File matched a skip condition (e.g. binary, non-UTF-8).
    SkippedUnreadable,
    /// File is not inside any project (no llmcontext.yaml, .llmctx/ or .git
    /// above it), so there is nowhere to store its context.
    SkippedNoProject,
}

/// How `process_file()` should behave.
///
/// `Default` is the everyday case: reuse existing context when the file has
/// not changed, prefer an `<<<LLMCTX` block when one is present.
#[derive(Debug, Clone, Copy, Default, PartialEq, Eq)]
pub struct ProcessOptions {
    /// Skip the extraction check and always regenerate via Ollama
    /// (`llmctx reindex`).
    pub force_ollama: bool,
    /// Process even when the store already holds context for this exact content.
    pub force: bool,
}

impl ProcessOptions {
    /// Resume-aware, extraction-first. What `llmctx index` and the daemon use.
    pub fn new() -> Self {
        Self::default()
    }

    /// Ignore stored context but still allow comment-block extraction.
    pub fn forced() -> Self {
        Self {
            force_ollama: false,
            force: true,
        }
    }

    /// Ignore stored context *and* bypass extraction — always call Ollama.
    pub fn force_ollama() -> Self {
        Self {
            force_ollama: true,
            force: true,
        }
    }
}

/// Full outcome of `process_file()`.
#[derive(Debug)]
pub struct ProcessResult {
    pub source: ProcessSource,
    /// The context body now stored for the file, or `None` if it was skipped
    /// or already current.
    pub context: Option<String>,
}

#[derive(Debug, Error)]
pub enum ProcessError {
    #[error("Could not read source file {path}: {source}")]
    ReadSource {
        path: String,
        #[source]
        source: std::io::Error,
    },

    #[error("Config error: {0}")]
    Config(#[from] config::ConfigError),

    #[error("Context store error: {0}")]
    Store(#[from] StoreError),

    #[error("Ollama error: {0}")]
    Ollama(#[from] OllamaError),
}

/// Minimum number of lines a file must have before Ollama is invoked.
/// Files below this threshold are skipped on the Ollama branch (extraction
/// runs regardless since it's trivially cheap).
const MIN_LINES_FOR_OLLAMA: usize = 5;

/// Field name of the source-content digest written into every context body.
/// The store keeps the same digest in its own column for lookups; this copy
/// lets a body be re-imported on its own (e.g. `llmctx migrate`).
const HASH_FIELD: &str = "HASH: ";

// ── Core function ─────────────────────────────────────────────────────────────

/// Process one file: detect an `<<<LLMCTX` comment block and extract it,
/// or fall back to Ollama generation.  In either case inject the project
/// header and write the result to the project's context store.
///
/// This is the single authoritative decision function.  Both the daemon's
/// save handler and the CLI's `index`/`extract` commands call this — they
/// never reimplement the branch logic themselves.
///
/// See [`ProcessOptions`] for the behaviour switches.
pub async fn process_file(
    path: &Path,
    client: &OllamaClient,
    opts: ProcessOptions,
) -> Result<ProcessResult, ProcessError> {
    // ── 1. Read source ────────────────────────────────────────────────────────
    let source = match std::fs::read_to_string(path) {
        Ok(s) => s,
        Err(e) if e.kind() == std::io::ErrorKind::InvalidData => {
            // Non-UTF-8 file (binary, image, etc.) — skip silently.
            debug!(?path, "skipping non-UTF-8 file");
            return Ok(skipped(ProcessSource::SkippedUnreadable));
        }
        Err(e) => {
            return Err(ProcessError::ReadSource {
                path: path.display().to_string(),
                source: e,
            })
        }
    };

    // ── 1a. Locate the project's context store ────────────────────────────────
    // Resolved before any Ollama work so a file outside every project costs
    // nothing, and never gets a stray `.llmctx/` created next to it.
    let (store, rel_path) = match ContextStore::open_for_file(path) {
        Ok(pair) => pair,
        Err(StoreError::NoProject { .. }) => {
            debug!(?path, "not inside an llmctx project — skipping");
            return Ok(skipped(ProcessSource::SkippedNoProject));
        }
        Err(e) => return Err(e.into()),
    };

    // ── 1b. Resume gate ───────────────────────────────────────────────────────
    // If the store already holds context for this exact content there is
    // nothing to regenerate. This is what makes `llmctx index` resumable: an
    // interrupted or partly-failed run picks up where it stopped instead of
    // re-sending every file to Ollama. Identical content stored under another
    // path (a rename, move or copy) is carried over the same way.
    //
    // Missing, stale or unreadable context all fall through to normal
    // processing, so this can never wedge on stale data.
    if !opts.force {
        match store.lookup(&rel_path, &content_hash(&source)) {
            Ok(Lookup::Current(_)) => {
                debug!(?path, "stored context already current for this content — skipping");
                return Ok(skipped(ProcessSource::UpToDate));
            }
            Ok(Lookup::Adopted { context, from }) => {
                info!(?path, %from, "identical content already had context — carried over");
                return Ok(ProcessResult {
                    source: ProcessSource::Reused,
                    context: Some(context.body),
                });
            }
            Ok(Lookup::Stale(_) | Lookup::Missing) => {}
            Err(e) => warn!(?path, "could not check stored context ({e}) — regenerating"),
        }
    }

    // ── 2. Find config (per-file walk-up) ────────────────────────────────────
    let config = match config::load_config_for_file(path) {
        Ok((_, config)) => config,
        Err(e) => {
            warn!(?path, "no llmcontext.yaml found, using defaults: {e}");
            ProjectConfig::default()
        }
    };

    // ── 3. Try comment-block extraction (unless force_ollama) ─────────────────
    if !opts.force_ollama {
        match extract::extract_llmctx_block(&source) {
            Ok(extracted) => {
                info!(?path, "extracted <<<LLMCTX block — Ollama skipped");

                // The hash must describe the file as it will exist *after* the
                // block is stripped, since that is what the next run reads.
                let hash = content_hash(&extracted.cleaned_source);
                let body = build_context_body(&config, &extracted.body, "llm", &hash);

                // Store the context *before* rewriting the source. Stripping
                // first would destroy the only copy of the block if the store
                // write then failed, leaving the file with neither.
                store.put(&rel_path, &hash, &body)?;

                // Now it is safe to strip the block from the source file.
                std::fs::write(path, &extracted.cleaned_source).map_err(|e| {
                    ProcessError::ReadSource {
                        path: path.display().to_string(),
                        source: e,
                    }
                })?;

                return Ok(ProcessResult {
                    source: ProcessSource::Extracted,
                    context: Some(body),
                });
            }
            Err(ExtractError::NoDelimiter) => {
                // Normal hand-written file — fall through to Ollama.
            }
            Err(e) => {
                // Block was found but is malformed.  Log and fall through.
                warn!(?path, "malformed <<<LLMCTX block ({e}) — falling back to Ollama");
            }
        }
    }

    // ── 4. Ollama branch ───────────────────────────────────────────────────────
    let line_count = source.lines().count();
    if line_count < MIN_LINES_FOR_OLLAMA {
        debug!(?path, line_count, "skipping Ollama — file too small");
        return Ok(skipped(ProcessSource::SkippedTooSmall));
    }

    // Upper bound too. A small local model has a context window of a few
    // thousand tokens, so a large file gets silently truncated server-side and
    // yields a useless answer — after a very long wait that usually ends in a
    // timeout. Skipping is faster and tells the truth.
    let max_bytes = config.ollama_max_bytes_or_default();
    if source.len() > max_bytes {
        warn!(
            ?path,
            bytes = source.len(),
            max_bytes,
            "skipping Ollama — file exceeds ollama_max_bytes"
        );
        return Ok(skipped(ProcessSource::SkippedTooLarge));
    }

    info!(?path, bytes = source.len(), "calling Ollama for context generation");
    let generated = client.generate(&config, &rel_path, &source).await?;

    // The Ollama branch leaves the file untouched, so the hash is of `source`.
    let hash = content_hash(&source);
    let body = build_context_body(&config, &generated.body, "ollama", &hash);
    store.put(&rel_path, &hash, &body)?;

    Ok(ProcessResult {
        source: ProcessSource::Ollama,
        context: Some(body),
    })
}

/// Context to pack for `path`: what is stored under its path — even if the
/// file changed since, because the daemon may still be regenerating — or
/// context carried over from identical content elsewhere (a rename).
///
/// Read-only apart from that carry-over: `Ok(None)` when the file is outside
/// every project or its project has no store yet, and no store is created.
pub fn stored_context(path: &Path) -> Result<Option<String>, ProcessError> {
    let Some((store, rel_path)) = ContextStore::open_existing_for_file(path)? else {
        return Ok(None);
    };
    let Ok(source) = std::fs::read_to_string(path) else {
        // Unreadable now, but whatever was stored for it is still the answer.
        return Ok(store.get(&rel_path)?.map(|c| c.body));
    };
    Ok(match store.lookup(&rel_path, &content_hash(&source))? {
        Lookup::Current(c) | Lookup::Stale(c) => Some(c.body),
        Lookup::Adopted { context, .. } => Some(context.body),
        Lookup::Missing => None,
    })
}

// ── Hash helper (used by daemon for debounce) ─────────────────────────────────

/// SHA-256 hex digest of `content`.  Stored with every context entry and
/// used by the daemon's debounce to detect files that changed while queued.
pub fn content_hash(content: &str) -> String {
    let mut h = Sha256::new();
    h.update(content.as_bytes());
    format!("{:x}", h.finalize())
}

/// Pull the `HASH:` value out of a context body, if present.
pub fn stored_hash(body: &str) -> Option<String> {
    body.lines()
        .find_map(|l| l.trim().strip_prefix(HASH_FIELD))
        .map(|h| h.trim().to_string())
}

// ── Helpers ───────────────────────────────────────────────────────────────────

fn skipped(source: ProcessSource) -> ProcessResult {
    ProcessResult {
        source,
        context: None,
    }
}

/// Compose the full context body: project header + source tag + hash +
/// six-field body.
fn build_context_body(
    config: &ProjectConfig,
    six_field_body: &str,
    source_tag: &str,
    hash: &str,
) -> String {
    format!(
        "{}SOURCE: {}\n{}{}\n\n{}",
        config.header_block(),
        source_tag,
        HASH_FIELD,
        hash,
        six_field_body
    )
}

// ── tests ─────────────────────────────────────────────────────────────────────

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn content_hash_is_deterministic() {
        let h1 = content_hash("hello world");
        let h2 = content_hash("hello world");
        assert_eq!(h1, h2);
    }

    #[test]
    fn content_hash_differs_for_different_content() {
        assert_ne!(content_hash("foo"), content_hash("bar"));
    }

    #[test]
    fn build_context_body_contains_all_sections() {
        let config = ProjectConfig {
            project: Some("Proj".into()),
            task: Some("T1".into()),
            ..Default::default()
        };
        let body = build_context_body(&config, "FILE: x.rs\nROLE: does things", "llm", "deadbeef");
        assert!(body.contains("PROJECT: Proj"));
        assert!(body.contains("SOURCE: llm"));
        assert!(body.contains("HASH: deadbeef"));
        assert!(body.contains("FILE: x.rs"));
    }

    #[test]
    fn stored_hash_round_trips_through_context_body() {
        let config = ProjectConfig::default();
        let hash = content_hash("some source");
        let body = build_context_body(&config, "FILE: x.rs", "ollama", &hash);
        assert_eq!(stored_hash(&body).as_deref(), Some(hash.as_str()));
    }

    #[test]
    fn stored_hash_absent_from_legacy_body() {
        // Bodies written before the HASH field existed must read as "unknown"
        // so they are regenerated rather than trusted.
        assert_eq!(stored_hash("PROJECT: p\nSOURCE: llm\n\nFILE: x.rs"), None);
    }

    #[test]
    fn process_options_presets_differ() {
        assert_eq!(
            ProcessOptions::new(),
            ProcessOptions {
                force_ollama: false,
                force: false
            }
        );
        assert!(ProcessOptions::forced().force);
        assert!(!ProcessOptions::forced().force_ollama);
        assert!(ProcessOptions::force_ollama().force_ollama);
        assert!(ProcessOptions::force_ollama().force);
    }

    // ── process_file against a real store (extraction path, no Ollama) ───────

    const BLOCK_SOURCE: &str = "# <<<LLMCTX
# FILE: app/main.py
# ROLE: Entry point
# EXPORTS: main()
# IMPORTS: NONE
# USED BY: NONE
# NOTES: NONE
# LLMCTX>>>

def main():
    pass
";

    fn project_with(rel: &str, content: &str) -> (tempfile::TempDir, std::path::PathBuf) {
        let dir = tempfile::TempDir::new().unwrap();
        std::fs::write(dir.path().join(config::CONFIG_FILENAME), "project: P\n").unwrap();
        let file = dir.path().join(rel);
        std::fs::create_dir_all(file.parent().unwrap()).unwrap();
        std::fs::write(&file, content).unwrap();
        (dir, file)
    }

    #[tokio::test]
    async fn extraction_stores_context_then_strips_block() {
        let (dir, file) = project_with("app/main.py", BLOCK_SOURCE);
        let client = OllamaClient::new();

        let r = process_file(&file, &client, ProcessOptions::new()).await.unwrap();
        assert_eq!(r.source, ProcessSource::Extracted);

        let cleaned = std::fs::read_to_string(&file).unwrap();
        assert!(!cleaned.contains("<<<LLMCTX"));
        assert!(dir.path().join(crate::store::STORE_DIR).is_dir());

        let body = stored_context(&file).unwrap().unwrap();
        assert!(body.contains("ROLE: Entry point"));
        assert!(body.contains("PROJECT: P"));
        assert_eq!(stored_hash(&body), Some(content_hash(&cleaned)));

        // Unchanged file: the resume gate answers without touching Ollama.
        let again = process_file(&file, &client, ProcessOptions::new()).await.unwrap();
        assert_eq!(again.source, ProcessSource::UpToDate);
    }

    #[tokio::test]
    async fn renamed_file_keeps_its_context() {
        let (dir, file) = project_with("app/main.py", BLOCK_SOURCE);
        let client = OllamaClient::new();
        process_file(&file, &client, ProcessOptions::new()).await.unwrap();

        let renamed = dir.path().join("app").join("entry.py");
        std::fs::rename(&file, &renamed).unwrap();

        let r = process_file(&renamed, &client, ProcessOptions::new()).await.unwrap();
        assert_eq!(r.source, ProcessSource::Reused);
        assert!(r.context.unwrap().contains("FILE: app/entry.py"));
        assert_eq!(stored_context(&file).unwrap(), None);
    }

    #[test]
    fn stored_context_never_creates_a_store() {
        let (dir, file) = project_with("a.py", "x = 1\n");
        assert_eq!(stored_context(&file).unwrap(), None);
        assert!(!dir.path().join(crate::store::STORE_DIR).exists());
    }
}
