// <<<LLMCTX
// FILE: crates/core/src/process.rs
// ROLE: Keystone decision function — ignore check, resume gate, block extraction or Ollama, then write the context store
// EXPORTS: process_file(), plan(), content_hash(), Plan, ProcessOptions, ProcessResult, ProcessSource, ProcessError
// IMPORTS: crates/core/src/store.rs, crates/core/src/config.rs, crates/core/src/extract.rs, crates/core/src/ollama.rs, crates/core/src/filter.rs, crates/core/src/fsutil.rs, crates/core/src/git.rs
// USED BY: crates/daemon/src/main.rs, crates/cli/src/main.rs
// NOTES: Daemon and CLI must call this function — never reimplement the branch logic themselves
// LLMCTX>>>

use std::path::{Path, PathBuf};

use sha2::{Digest, Sha256};
use thiserror::Error;
use tracing::{debug, info, warn};

use crate::{
    config::{self, ProjectConfig},
    extract::{self, ExtractError, ExtractedContext},
    filter, fsutil, git,
    ollama::{OllamaClient, OllamaError},
    store::{self, ContextStore, Donor, Lookup, StoreError},
};

// ── Public types ─────────────────────────────────────────────────────────────

/// What `process_file()` did.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum ProcessSource {
    /// Context came from an `<<<LLMCTX` block, which was then stripped.
    Extracted,
    /// Context came from an `<<<LLMCTX` block that is committed in git, so
    /// it was stored but left in the file (stripping it would dirty the
    /// working tree of everyone who has it).
    ExtractedKept,
    /// Context was generated by Ollama.
    Ollama,
    /// The store already holds context for this exact file content.
    UpToDate,
    /// Context was carried over from another path with identical content
    /// (the file was renamed, moved or copied).
    Reused,
    /// File was too small to bother Ollama (< MIN_LINES lines).
    SkippedTooSmall,
    /// File was too large to be worth sending to a small local model.
    SkippedTooLarge,
    /// File matched a skip condition (e.g. binary, non-UTF-8).
    SkippedUnreadable,
    /// File is not inside any project (no llmcontext.yaml, .llmctx/ or .git
    /// above it), so there is nowhere to store its context.
    SkippedNoProject,
    /// File is excluded by .gitignore/.ignore, `llmctx_ignore`, or is hidden.
    SkippedIgnored,
}

impl ProcessSource {
    /// True when the file now has stored context that matches its content.
    pub fn has_context(self) -> bool {
        matches!(
            self,
            Self::Extracted | Self::ExtractedKept | Self::Ollama | Self::UpToDate | Self::Reused
        )
    }

    /// Short human-readable explanation, shared by the CLI and the daemon's
    /// status messages.
    pub fn describe(self) -> &'static str {
        match self {
            Self::Extracted => "extracted <<<LLMCTX block",
            Self::ExtractedKept => "stored the committed <<<LLMCTX block (left in the file)",
            Self::Ollama => "generated via Ollama",
            Self::UpToDate => "already current",
            Self::Reused => "carried over from an identical file",
            Self::SkippedTooSmall => "skipped: too small to need context",
            Self::SkippedTooLarge => "skipped: larger than ollama_max_bytes",
            Self::SkippedUnreadable => "skipped: binary or not UTF-8",
            Self::SkippedNoProject => {
                "skipped: not inside an llmctx project (run `llmctx init` in the project root)"
            }
            Self::SkippedIgnored => {
                "skipped: ignored by .gitignore/.ignore, llmctx_ignore, or a hidden path"
            }
        }
    }
}

/// How `process_file()` should behave.
///
/// `Default` is the everyday case: reuse existing context when the file has
/// not changed, prefer an `<<<LLMCTX` block when one is present.
#[derive(Debug, Clone, Copy, Default, PartialEq, Eq)]
pub struct ProcessOptions {
    /// Skip the extraction check and always regenerate via Ollama
    /// (`llmctx reindex`).
    pub force_ollama: bool,
    /// Process even when the store already holds context for this exact content.
    pub force: bool,
}

impl ProcessOptions {
    /// Resume-aware, extraction-first. What `llmctx index` and the daemon use.
    pub fn new() -> Self {
        Self::default()
    }

    /// Ignore stored context but still allow comment-block extraction.
    pub fn forced() -> Self {
        Self {
            force_ollama: false,
            force: true,
        }
    }

    /// Ignore stored context *and* bypass extraction — always call Ollama.
    pub fn force_ollama() -> Self {
        Self {
            force_ollama: true,
            force: true,
        }
    }
}

/// Full outcome of `process_file()`.
#[derive(Debug)]
pub struct ProcessResult {
    pub source: ProcessSource,
    /// The six fields now stored for the file, when this call stored them.
    pub context: Option<String>,
}

#[derive(Debug, Error)]
pub enum ProcessError {
    #[error("Could not read source file {path}: {source}")]
    ReadSource {
        path: String,
        #[source]
        source: std::io::Error,
    },

    #[error("Could not rewrite source file {path}: {source}")]
    WriteSource {
        path: String,
        #[source]
        source: std::io::Error,
    },

    // Transparent: these errors already say what failed, and wrapping them
    // with a prefix made every error chain print the same message twice.
    #[error(transparent)]
    Config(#[from] config::ConfigError),

    #[error(transparent)]
    Store(#[from] StoreError),

    #[error(transparent)]
    Ollama(#[from] OllamaError),
}

/// Minimum number of lines a file must have before Ollama is invoked.
/// Files below this threshold are skipped on the Ollama branch (extraction
/// runs regardless since it's trivially cheap).
const MIN_LINES_FOR_OLLAMA: usize = 5;

// ── Core function ─────────────────────────────────────────────────────────────

/// What [`process_file`] will do for a file, decided without writing anything
/// or calling Ollama. The daemon uses it to answer a save that needs no model
/// at once, and to debounce and queue only real generation work.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum Plan {
    /// Nothing will be done, for this reason.
    Skip(ProcessSource),
    /// Stored context already matches the content.
    UpToDate,
    /// Context will be carried over from identical content elsewhere.
    Reuse,
    /// An `<<<LLMCTX` block will be extracted.
    Extract,
    /// Ollama will be called.
    Generate,
}

/// Decide what [`process_file`] would do right now. Read-only.
pub fn plan(path: &Path, opts: ProcessOptions) -> Result<Plan, ProcessError> {
    Ok(match prepare(path, opts)? {
        Prepared::Skip(source) => Plan::Skip(source),
        Prepared::Ready { step, .. } => match step {
            Step::UpToDate => Plan::UpToDate,
            Step::Reuse(_) => Plan::Reuse,
            Step::Extract(_) => Plan::Extract,
            Step::Generate => Plan::Generate,
        },
    })
}

/// Process one file: detect an `<<<LLMCTX` comment block and extract it,
/// or fall back to Ollama generation, and store the six fields in the
/// project's context store.
///
/// This is the single authoritative decision function.  Both the daemon's
/// save handler and the CLI's `index`/`extract` commands call this — they
/// never reimplement the branch logic themselves. The decisions live in
/// [`prepare`], which [`plan`] shares.
///
/// See [`ProcessOptions`] for the behaviour switches.
pub async fn process_file(
    path: &Path,
    client: &OllamaClient,
    opts: ProcessOptions,
) -> Result<ProcessResult, ProcessError> {
    let (root, config, source, step) = match prepare(path, opts)? {
        Prepared::Skip(source) => return Ok(skipped(source)),
        Prepared::Ready {
            root,
            config,
            source,
            step,
        } => (root, config, source, step),
    };
    if matches!(step, Step::UpToDate) {
        return Ok(skipped(ProcessSource::UpToDate));
    }

    let store = ContextStore::open(&root)?;
    let rel_path = store.rel_key(path)?;
    let hash = content_hash(&source);

    match step {
        Step::UpToDate => unreachable!("handled above"),

        Step::Reuse(donor) => {
            let adopted = store.adopt(&rel_path, &hash, &donor)?;
            info!(
                ?path,
                from = %donor.context.rel_path,
                "identical content already had context — carried over"
            );
            Ok(ProcessResult {
                source: ProcessSource::Reused,
                context: Some(adopted.fields),
            })
        }

        Step::Extract(extracted) => {
            let fields = store::set_field(&clean_fields(&extracted.body), "FILE", &rel_path);

            if block_is_committed(path) {
                // Someone committed this block on purpose. Stripping it would
                // show up as a change in everyone's working tree, so store it
                // and leave the file alone.
                store.put(&rel_path, &hash, "llm", &fields)?;
                info!(
                    ?path,
                    "<<<LLMCTX block is committed in git — stored, left in file"
                );
                return Ok(ProcessResult {
                    source: ProcessSource::ExtractedKept,
                    context: Some(fields),
                });
            }

            info!(?path, "extracted <<<LLMCTX block — Ollama skipped");
            // The hash must describe the file as it will exist *after* the
            // block is stripped, since that is what the next run reads.
            let cleaned_hash = content_hash(&extracted.cleaned_source);

            // Store the context *before* rewriting the source. Stripping
            // first would destroy the only copy of the block if the store
            // write then failed, leaving the file with neither.
            store.put(&rel_path, &cleaned_hash, "llm", &fields)?;

            // Now it is safe to strip the block from the source file —
            // atomically, so a crash can never leave it half-written.
            fsutil::replace_file(path, extracted.cleaned_source.as_bytes()).map_err(|e| {
                ProcessError::WriteSource {
                    path: path.display().to_string(),
                    source: e,
                }
            })?;

            Ok(ProcessResult {
                source: ProcessSource::Extracted,
                context: Some(fields),
            })
        }

        Step::Generate => {
            info!(
                ?path,
                bytes = source.len(),
                "calling Ollama for context generation"
            );
            let generated = client.generate(&config, &rel_path, &source).await?;
            // The Ollama branch leaves the file untouched, so the hash is of
            // `source`.
            store.put(&rel_path, &hash, "ollama", &generated.fields)?;
            Ok(ProcessResult {
                source: ProcessSource::Ollama,
                context: Some(generated.fields),
            })
        }
    }
}

// ── Decision logic ────────────────────────────────────────────────────────────

// Built once per file and consumed immediately, so the size difference
// between the variants costs nothing worth a heap allocation.
#[allow(clippy::large_enum_variant)]
enum Prepared {
    Skip(ProcessSource),
    Ready {
        root: PathBuf,
        config: ProjectConfig,
        source: String,
        step: Step,
    },
}

enum Step {
    UpToDate,
    Reuse(Donor),
    Extract(ExtractedContext),
    Generate,
}

/// Every decision `process_file` makes, in order, without side effects.
fn prepare(path: &Path, opts: ProcessOptions) -> Result<Prepared, ProcessError> {
    // ── 1. Project, config and ignore rules ───────────────────────────────────
    // Decided before anything is read or created: a file outside every
    // project, or one `llmctx index` would skip (.gitignore, llmctx_ignore,
    // hidden files like .env), is never read, sent to Ollama or stored —
    // whichever entry point it arrived through.
    let Some(root) = store::project_root_for_file(path) else {
        debug!(?path, "not inside an llmctx project — skipping");
        return Ok(Prepared::Skip(ProcessSource::SkippedNoProject));
    };
    let config = match config::load_config_for_file(path) {
        Ok((_, config)) => config,
        Err(config::ConfigError::NotFound { .. }) => ProjectConfig::default(),
        Err(e) => {
            warn!(?path, "could not load llmcontext.yaml, using defaults: {e}");
            ProjectConfig::default()
        }
    };
    if filter::is_ignored(&root, path, &config.llmctx_ignore) {
        debug!(?path, "ignored by .gitignore/llmctx_ignore — skipping");
        return Ok(Prepared::Skip(ProcessSource::SkippedIgnored));
    }

    // ── 2. Read source ────────────────────────────────────────────────────────
    let source = match std::fs::read_to_string(path) {
        Ok(s) => s,
        Err(e) if e.kind() == std::io::ErrorKind::InvalidData => {
            // Non-UTF-8 file (binary, image, etc.) — skip silently.
            debug!(?path, "skipping non-UTF-8 file");
            return Ok(Prepared::Skip(ProcessSource::SkippedUnreadable));
        }
        Err(e) => {
            return Err(ProcessError::ReadSource {
                path: path.display().to_string(),
                source: e,
            })
        }
    };

    let ready = |step| Prepared::Ready {
        root: root.clone(),
        config: config.clone(),
        source: source.clone(),
        step,
    };

    // ── 3. Resume gate ────────────────────────────────────────────────────────
    // If the store already holds context for this exact content there is
    // nothing to regenerate. This is what makes `llmctx index` resumable: an
    // interrupted or partly-failed run picks up where it stopped instead of
    // re-sending every file to Ollama. Identical content stored under another
    // path (a rename, move or copy) is carried over the same way.
    //
    // Missing, stale or unreadable context all fall through to normal
    // processing, so this can never wedge on stale data.
    if !opts.force {
        let lookup = ContextStore::open_existing(&root).and_then(|store| match store {
            Some(store) => {
                let rel_path = store.rel_key(path)?;
                store.resolve(&rel_path, &content_hash(&source))
            }
            None => Ok(Lookup::Missing),
        });
        match lookup {
            Ok(Lookup::Current(_)) => {
                debug!(
                    ?path,
                    "stored context already current for this content — skipping"
                );
                return Ok(ready(Step::UpToDate));
            }
            Ok(Lookup::Found(donor)) => return Ok(ready(Step::Reuse(donor))),
            Ok(Lookup::Stale(_) | Lookup::Missing) => {}
            Err(e) => warn!(?path, "could not check stored context ({e}) — regenerating"),
        }
    }

    // ── 4. Comment-block extraction (unless force_ollama) ─────────────────────
    if !opts.force_ollama {
        match extract::extract_llmctx_block(&source) {
            Ok(extracted) => return Ok(ready(Step::Extract(extracted))),
            Err(ExtractError::NoDelimiter) => {
                // Normal hand-written file — fall through to Ollama.
            }
            Err(e) => {
                // Block was found but is malformed.  Log and fall through.
                warn!(
                    ?path,
                    "malformed <<<LLMCTX block ({e}) — falling back to Ollama"
                );
            }
        }
    }

    // ── 5. Ollama size gates ──────────────────────────────────────────────────
    let line_count = source.lines().count();
    if line_count < MIN_LINES_FOR_OLLAMA {
        debug!(?path, line_count, "skipping Ollama — file too small");
        return Ok(Prepared::Skip(ProcessSource::SkippedTooSmall));
    }

    // Upper bound too. A small local model has a context window of a few
    // thousand tokens, so a large file gets silently truncated server-side and
    // yields a useless answer — after a very long wait that usually ends in a
    // timeout. Skipping is faster and tells the truth.
    let max_bytes = config.ollama_max_bytes_or_default();
    if source.len() > max_bytes {
        warn!(
            ?path,
            bytes = source.len(),
            max_bytes,
            "skipping Ollama — file exceeds ollama_max_bytes"
        );
        return Ok(Prepared::Skip(ProcessSource::SkippedTooLarge));
    }

    Ok(ready(Step::Generate))
}

// ── Hash helper ───────────────────────────────────────────────────────────────

/// SHA-256 hex digest of `content`.  Stored with every context entry and
/// used by the daemon's debounce to detect files that changed while queued.
/// Must match `contentHash()` in the VS Code extension byte for byte.
pub fn content_hash(content: &str) -> String {
    let mut h = Sha256::new();
    h.update(content.as_bytes());
    format!("{:x}", h.finalize())
}

// ── Helpers ───────────────────────────────────────────────────────────────────

fn skipped(source: ProcessSource) -> ProcessResult {
    ProcessResult {
        source,
        context: None,
    }
}

/// True when the version of `path` committed at HEAD already starts with an
/// `<<<LLMCTX` block — i.e. the block is part of the repository, not
/// something an LLM just wrote.
fn block_is_committed(path: &Path) -> bool {
    git::committed_version(path)
        .map(|head| extract::extract_llmctx_block(&head).is_ok())
        .unwrap_or(false)
}

/// Drop the empty lines that closing comment markers (`-->`, `*/`) leave in
/// an extracted block.
fn clean_fields(body: &str) -> String {
    body.lines()
        .map(str::trim_end)
        .filter(|l| !l.trim().is_empty())
        .collect::<Vec<_>>()
        .join("\n")
}

// ── tests ─────────────────────────────────────────────────────────────────────

#[cfg(test)]
mod tests {
    use super::*;
    use std::{fs, process::Command};
    use tempfile::TempDir;

    #[test]
    fn content_hash_is_deterministic() {
        let h1 = content_hash("hello world");
        let h2 = content_hash("hello world");
        assert_eq!(h1, h2);
    }

    #[test]
    fn content_hash_differs_for_different_content() {
        assert_ne!(content_hash("foo"), content_hash("bar"));
    }

    #[test]
    fn process_options_presets_differ() {
        assert_eq!(
            ProcessOptions::new(),
            ProcessOptions {
                force_ollama: false,
                force: false
            }
        );
        assert!(ProcessOptions::forced().force);
        assert!(!ProcessOptions::forced().force_ollama);
        assert!(ProcessOptions::force_ollama().force_ollama);
        assert!(ProcessOptions::force_ollama().force);
    }

    #[test]
    fn clean_fields_drops_blank_marker_lines() {
        assert_eq!(clean_fields("FILE: a\n\nROLE: r  \n"), "FILE: a\nROLE: r");
    }

    // ── process_file against a real store (extraction path, no Ollama) ───────

    const BLOCK_SOURCE: &str = "# <<<LLMCTX
# FILE: wrong/path.py
# ROLE: Entry point
# EXPORTS: main()
# IMPORTS: NONE
# USED BY: NONE
# NOTES: NONE
# LLMCTX>>>

def main():
    pass
";

    fn project_with(rel: &str, content: &str) -> (TempDir, PathBuf) {
        let dir = TempDir::new().unwrap();
        fs::write(dir.path().join(config::CONFIG_FILENAME), "project: P\n").unwrap();
        let file = dir.path().join(rel);
        fs::create_dir_all(file.parent().unwrap()).unwrap();
        fs::write(&file, content).unwrap();
        (dir, file)
    }

    fn stored(file: &Path) -> Option<store::StoredContext> {
        let (store, rel) = ContextStore::open_existing_for_file(file).unwrap()?;
        store.get(&rel).unwrap()
    }

    #[tokio::test]
    async fn extraction_stores_context_then_strips_block() {
        let (dir, file) = project_with("app/main.py", BLOCK_SOURCE);
        let client = OllamaClient::new();

        let r = process_file(&file, &client, ProcessOptions::new())
            .await
            .unwrap();
        assert_eq!(r.source, ProcessSource::Extracted);

        let cleaned = fs::read_to_string(&file).unwrap();
        assert!(!cleaned.contains("<<<LLMCTX"));
        assert!(dir.path().join(store::STORE_DIR).is_dir());

        let ctx = stored(&file).unwrap();
        assert!(ctx.fields.contains("ROLE: Entry point"));
        // FILE is always the real path, whatever the block claimed.
        assert!(ctx.fields.starts_with("FILE: app/main.py\n"));
        // The project header is never stored — it is rendered at pack time.
        assert!(!ctx.fields.contains("PROJECT:"));
        assert_eq!(ctx.content_hash, content_hash(&cleaned));
        assert_eq!(ctx.source, "llm");

        // Unchanged file: the resume gate answers without touching Ollama.
        let again = process_file(&file, &client, ProcessOptions::new())
            .await
            .unwrap();
        assert_eq!(again.source, ProcessSource::UpToDate);
    }

    #[tokio::test]
    async fn plan_predicts_process_file_without_side_effects() {
        let (dir, file) = project_with("app/main.py", BLOCK_SOURCE);
        assert_eq!(plan(&file, ProcessOptions::new()).unwrap(), Plan::Extract);
        // Planning created nothing.
        assert!(!dir.path().join(store::STORE_DIR).exists());
        assert_eq!(fs::read_to_string(&file).unwrap(), BLOCK_SOURCE);

        process_file(&file, &OllamaClient::new(), ProcessOptions::new())
            .await
            .unwrap();
        assert_eq!(plan(&file, ProcessOptions::new()).unwrap(), Plan::UpToDate);

        let tiny = dir.path().join("tiny.py");
        fs::write(&tiny, "x = 1\n").unwrap();
        assert_eq!(
            plan(&tiny, ProcessOptions::new()).unwrap(),
            Plan::Skip(ProcessSource::SkippedTooSmall)
        );
        let big = dir.path().join("big.py");
        fs::write(&big, "x = 1\n".repeat(10)).unwrap();
        assert_eq!(plan(&big, ProcessOptions::new()).unwrap(), Plan::Generate);
    }

    #[tokio::test]
    async fn renamed_file_keeps_its_context() {
        let (dir, file) = project_with("app/main.py", BLOCK_SOURCE);
        let client = OllamaClient::new();
        process_file(&file, &client, ProcessOptions::new())
            .await
            .unwrap();

        let renamed = dir.path().join("app").join("entry.py");
        fs::rename(&file, &renamed).unwrap();

        let r = process_file(&renamed, &client, ProcessOptions::new())
            .await
            .unwrap();
        assert_eq!(r.source, ProcessSource::Reused);
        assert!(r.context.unwrap().contains("FILE: app/entry.py"));
        assert_eq!(stored(&file), None);
    }

    #[tokio::test]
    async fn ignored_and_hidden_files_are_never_touched() {
        let (dir, _) = project_with(".gitignore", "generated/\n");
        let env = dir.path().join(".env");
        fs::write(&env, BLOCK_SOURCE).unwrap();
        let gen = dir.path().join("generated").join("x.py");
        fs::create_dir_all(gen.parent().unwrap()).unwrap();
        fs::write(&gen, BLOCK_SOURCE).unwrap();
        let client = OllamaClient::new();

        for file in [&env, &gen] {
            let r = process_file(file, &client, ProcessOptions::new())
                .await
                .unwrap();
            assert_eq!(r.source, ProcessSource::SkippedIgnored);
            assert_eq!(fs::read_to_string(file).unwrap(), BLOCK_SOURCE);
        }
        assert!(!dir.path().join(store::STORE_DIR).exists());
    }

    #[tokio::test]
    async fn documentation_showing_the_format_is_left_alone() {
        let doc = format!("# How to write a block\n\n```python\n{BLOCK_SOURCE}```\n");
        let (dir, file) = project_with("docs/format.md", &doc);
        // Keep Ollama out of it: the point is only that nothing is extracted.
        fs::write(
            dir.path().join(config::CONFIG_FILENAME),
            "project: P\nollama_max_bytes: 10\n",
        )
        .unwrap();
        let client = OllamaClient::new();
        // Too small for Ollama, and crucially: not extracted or rewritten.
        let r = process_file(&file, &client, ProcessOptions::new())
            .await
            .unwrap();
        assert_ne!(r.source, ProcessSource::Extracted);
        assert_eq!(fs::read_to_string(&file).unwrap(), doc);
    }

    #[tokio::test]
    async fn committed_blocks_are_stored_but_left_in_the_file() {
        let (dir, file) = project_with("app/main.py", BLOCK_SOURCE);
        let git = |args: &[&str]| {
            Command::new("git")
                .arg("-C")
                .arg(dir.path())
                .args(args)
                .output()
                .map(|o| o.status.success())
                .unwrap_or(false)
        };
        if !git(&["init", "-q"]) {
            eprintln!("git not available — skipping");
            return;
        }
        assert!(git(&["add", "."]));
        assert!(git(&[
            "-c",
            "user.name=t",
            "-c",
            "user.email=t@t",
            "commit",
            "-q",
            "-m",
            "init"
        ]));

        let client = OllamaClient::new();
        let r = process_file(&file, &client, ProcessOptions::new())
            .await
            .unwrap();
        assert_eq!(r.source, ProcessSource::ExtractedKept);
        assert_eq!(fs::read_to_string(&file).unwrap(), BLOCK_SOURCE);
        assert!(stored(&file).unwrap().fields.contains("ROLE: Entry point"));

        let again = process_file(&file, &client, ProcessOptions::new())
            .await
            .unwrap();
        assert_eq!(again.source, ProcessSource::UpToDate);
    }
}
