// <<<LLMCTX
// FILE: crates/core/src/process.rs
// ROLE: Keystone decision function — extract comment block or fall back to Ollama, then write ADS
// EXPORTS: process_file(), ProcessResult, ProcessSource, ProcessError
// IMPORTS: crates/core/src/ads.rs, crates/core/src/config.rs, crates/core/src/extract.rs, crates/core/src/ollama.rs
// USED BY: crates/daemon/src/main.rs, crates/cli/src/main.rs
// NOTES: Daemon and CLI must call this function — never reimplement the branch logic themselves
// LLMCTX>>>

use std::path::Path;

use sha2::{Digest, Sha256};
use thiserror::Error;
use tracing::{debug, info, warn};

use crate::{
    ads::{self, AdsError},
    config::{self, ProjectConfig},
    extract::{self, ExtractError},
    ollama::{OllamaClient, OllamaError},
};

// ── Public types ─────────────────────────────────────────────────────────────

/// Which code path produced the ADS content.
#[derive(Debug, Clone, PartialEq, Eq)]
pub enum ProcessSource {
    /// Context came from an `<<<LLMCTX` comment block in the file itself.
    Extracted,
    /// Context was generated by Ollama.
    Ollama,
    /// ADS already holds context for this exact file content — nothing to do.
    UpToDate,
    /// File was too small to bother Ollama (< MIN_LINES lines).
    SkippedTooSmall,
    /// File was too large to be worth sending to a small local model.
    SkippedTooLarge,
    /// File matched a skip condition (e.g. binary, non-UTF-8).
    SkippedUnreadable,
}

/// How `process_file()` should behave.
///
/// `Default` is the everyday case: reuse existing context when the file has
/// not changed, prefer an `<<<LLMCTX` block when one is present.
#[derive(Debug, Clone, Copy, Default, PartialEq, Eq)]
pub struct ProcessOptions {
    /// Skip the extraction check and always regenerate via Ollama
    /// (`llmctx reindex`).
    pub force_ollama: bool,
    /// Process even when ADS already holds context for this exact content.
    pub force: bool,
}

impl ProcessOptions {
    /// Resume-aware, extraction-first. What `llmctx index` and the daemon use.
    pub fn new() -> Self {
        Self::default()
    }

    /// Ignore existing ADS but still allow comment-block extraction.
    pub fn forced() -> Self {
        Self {
            force_ollama: false,
            force: true,
        }
    }

    /// Ignore existing ADS *and* bypass extraction — always call Ollama.
    pub fn force_ollama() -> Self {
        Self {
            force_ollama: true,
            force: true,
        }
    }
}

/// Full outcome of `process_file()`.
#[derive(Debug)]
pub struct ProcessResult {
    pub source: ProcessSource,
    /// The body that was written to ADS, or `None` if the file was skipped.
    pub ads_body: Option<String>,
}

#[derive(Debug, Error)]
pub enum ProcessError {
    #[error("Could not read source file {path}: {source}")]
    ReadSource {
        path: String,
        #[source]
        source: std::io::Error,
    },

    #[error("Config error: {0}")]
    Config(#[from] config::ConfigError),

    #[error("ADS write error: {0}")]
    Ads(#[from] AdsError),

    #[error("Ollama error: {0}")]
    Ollama(#[from] OllamaError),
}

/// Minimum number of lines a file must have before Ollama is invoked.
/// Files below this threshold are skipped on the Ollama branch (extraction
/// runs regardless since it's trivially cheap).
const MIN_LINES_FOR_OLLAMA: usize = 5;

/// Field name of the source-content digest stored inside every ADS body.
/// `is_up_to_date()` compares against this to decide whether a file can be
/// skipped, which is what makes `llmctx index` resumable.
const HASH_FIELD: &str = "HASH: ";

// ── Core function ─────────────────────────────────────────────────────────────

/// Process one file: detect an `<<<LLMCTX` comment block and extract it,
/// or fall back to Ollama generation.  In either case inject the project
/// header and version stamp and write to ADS.
///
/// This is the single authoritative decision function.  Both the daemon's
/// save handler and the CLI's `index`/`extract` commands call this — they
/// never reimplement the branch logic themselves.
///
/// See [`ProcessOptions`] for the behaviour switches.
pub async fn process_file(
    path: &Path,
    client: &OllamaClient,
    opts: ProcessOptions,
) -> Result<ProcessResult, ProcessError> {
    // ── 1. Read source ────────────────────────────────────────────────────────
    let source = match std::fs::read_to_string(path) {
        Ok(s) => s,
        Err(e) if e.kind() == std::io::ErrorKind::InvalidData => {
            // Non-UTF-8 file (binary, image, etc.) — skip silently.
            debug!(?path, "skipping non-UTF-8 file");
            return Ok(ProcessResult {
                source: ProcessSource::SkippedUnreadable,
                ads_body: None,
            });
        }
        Err(e) => {
            return Err(ProcessError::ReadSource {
                path: path.display().to_string(),
                source: e,
            })
        }
    };

    // ── 1b. Resume gate ───────────────────────────────────────────────────────
    // If ADS already holds context stamped with this exact content hash there
    // is nothing to regenerate. This is what makes `llmctx index` resumable:
    // an interrupted or partly-failed run picks up where it stopped instead of
    // re-sending every file to Ollama.
    //
    // A missing stream, a stale ADS version, or a hash mismatch all fall
    // through to normal processing, so this can never wedge on stale data.
    if !opts.force && is_up_to_date(path, &source) {
        debug!(?path, "ADS already current for this content — skipping");
        return Ok(ProcessResult {
            source: ProcessSource::UpToDate,
            ads_body: None,
        });
    }

    // ── 2. Find config (per-file walk-up) ────────────────────────────────────
    let (config_path, config) = match config::load_config_for_file(path) {
        Ok(pair) => pair,
        Err(e) => {
            warn!(?path, "no llmcontext.yaml found, using defaults: {e}");
            (path.to_path_buf(), ProjectConfig::default())
        }
    };

    // Relative path for use in prompts and ADS body.
    let rel_path = relative_to_config(&config_path, path);

    // ── 3. Try comment-block extraction (unless force_ollama) ─────────────────
    if !opts.force_ollama {
        match extract::extract_llmctx_block(&source) {
            Ok(extracted) => {
                info!(?path, "extracted <<<LLMCTX block — Ollama skipped");

                // The hash must describe the file as it will exist *after* the
                // block is stripped, since that is what the next run reads.
                let ads_body = build_ads_body(
                    &config,
                    &extracted.body,
                    "llm",
                    &content_hash(&extracted.cleaned_source),
                );

                // Write ADS *before* rewriting the source. Stripping first
                // would destroy the only copy of the block if the ADS write
                // then failed, leaving the file with neither.
                ads::write_ads(path, &ads_body)?;

                // Now it is safe to strip the block from the source file.
                std::fs::write(path, &extracted.cleaned_source).map_err(|e| {
                    ProcessError::ReadSource {
                        path: path.display().to_string(),
                        source: e,
                    }
                })?;

                return Ok(ProcessResult {
                    source: ProcessSource::Extracted,
                    ads_body: Some(ads_body),
                });
            }
            Err(ExtractError::NoDelimiter) => {
                // Normal hand-written file — fall through to Ollama.
            }
            Err(e) => {
                // Block was found but is malformed.  Log and fall through.
                warn!(?path, "malformed <<<LLMCTX block ({e}) — falling back to Ollama");
            }
        }
    }

    // ── 4. Ollama branch ───────────────────────────────────────────────────────
    let line_count = source.lines().count();
    if line_count < MIN_LINES_FOR_OLLAMA {
        debug!(?path, line_count, "skipping Ollama — file too small");
        return Ok(ProcessResult {
            source: ProcessSource::SkippedTooSmall,
            ads_body: None,
        });
    }

    // Upper bound too. A small local model has a context window of a few
    // thousand tokens, so a large file gets silently truncated server-side and
    // yields a useless answer — after a very long wait that usually ends in a
    // timeout. Skipping is faster and tells the truth.
    let max_bytes = config.ollama_max_bytes_or_default();
    if source.len() > max_bytes {
        warn!(
            ?path,
            bytes = source.len(),
            max_bytes,
            "skipping Ollama — file exceeds ollama_max_bytes"
        );
        return Ok(ProcessResult {
            source: ProcessSource::SkippedTooLarge,
            ads_body: None,
        });
    }

    info!(?path, bytes = source.len(), "calling Ollama for context generation");
    let generated = client.generate(&config, &rel_path, &source).await?;

    // The Ollama branch leaves the file untouched, so the hash is of `source`.
    let ads_body = build_ads_body(&config, &generated.body, "ollama", &content_hash(&source));
    ads::write_ads(path, &ads_body)?;

    Ok(ProcessResult {
        source: ProcessSource::Ollama,
        ads_body: Some(ads_body),
    })
}

// ── Hash helper (used by daemon for debounce) ─────────────────────────────────

/// SHA-256 hex digest of `content`.  The daemon compares this against the
/// hash stored at the time of the last ADS write to decide whether to skip
/// a queued Ollama call.
pub fn content_hash(content: &str) -> String {
    let mut h = Sha256::new();
    h.update(content.as_bytes());
    format!("{:x}", h.finalize())
}

/// Returns `true` when ADS already holds context generated from exactly this
/// content.
///
/// Deliberately total: every failure mode (no stream, unsupported platform,
/// stale ADS version, unreadable stream, missing or mismatched `HASH:` field)
/// answers `false`, meaning "regenerate". Being wrong in that direction costs
/// one redundant generation; being wrong the other way would silently serve
/// stale context.
pub fn is_up_to_date(path: &Path, source: &str) -> bool {
    match ads::read_ads(path) {
        Ok(body) => stored_hash(&body).is_some_and(|h| h == content_hash(source)),
        Err(_) => false,
    }
}

/// Pull the `HASH:` value out of an ADS body, if present.
fn stored_hash(ads_body: &str) -> Option<String> {
    ads_body
        .lines()
        .find_map(|l| l.trim().strip_prefix(HASH_FIELD))
        .map(|h| h.trim().to_string())
}

// ── Helpers ───────────────────────────────────────────────────────────────────

/// Compose the full ADS body: project header + six-field body + source tag.
///
/// The version stamp is prepended by `ads::write_ads()`, not here, so
/// callers never see it and never need to strip it.
fn build_ads_body(
    config: &ProjectConfig,
    six_field_body: &str,
    source_tag: &str,
    hash: &str,
) -> String {
    format!(
        "{}SOURCE: {}\n{}{}\n\n{}",
        config.header_block(),
        source_tag,
        HASH_FIELD,
        hash,
        six_field_body
    )
}

/// Compute the file path relative to the directory containing `config_path`.
/// Falls back to the file's filename if relativisation fails.
fn relative_to_config(config_path: &Path, file_path: &Path) -> String {
    let base = config_path
        .parent()
        .unwrap_or_else(|| Path::new("."));
    file_path
        .strip_prefix(base)
        .unwrap_or(file_path)
        .display()
        .to_string()
}

// ── tests ─────────────────────────────────────────────────────────────────────

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn content_hash_is_deterministic() {
        let h1 = content_hash("hello world");
        let h2 = content_hash("hello world");
        assert_eq!(h1, h2);
    }

    #[test]
    fn content_hash_differs_for_different_content() {
        assert_ne!(content_hash("foo"), content_hash("bar"));
    }

    #[test]
    fn build_ads_body_contains_all_sections() {
        let config = ProjectConfig {
            project: Some("Proj".into()),
            task: Some("T1".into()),
            ..Default::default()
        };
        let body = build_ads_body(&config, "FILE: x.rs\nROLE: does things", "llm", "deadbeef");
        assert!(body.contains("PROJECT: Proj"));
        assert!(body.contains("SOURCE: llm"));
        assert!(body.contains("HASH: deadbeef"));
        assert!(body.contains("FILE: x.rs"));
    }

    #[test]
    fn stored_hash_round_trips_through_ads_body() {
        let config = ProjectConfig::default();
        let hash = content_hash("some source");
        let body = build_ads_body(&config, "FILE: x.rs", "ollama", &hash);
        assert_eq!(stored_hash(&body).as_deref(), Some(hash.as_str()));
    }

    #[test]
    fn stored_hash_absent_from_legacy_body() {
        // Bodies written before the HASH field existed must read as "unknown"
        // so they are regenerated rather than trusted.
        assert_eq!(stored_hash("PROJECT: p\nSOURCE: llm\n\nFILE: x.rs"), None);
    }

    #[test]
    fn process_options_presets_differ() {
        assert_eq!(
            ProcessOptions::new(),
            ProcessOptions {
                force_ollama: false,
                force: false
            }
        );
        assert!(ProcessOptions::forced().force);
        assert!(!ProcessOptions::forced().force_ollama);
        assert!(ProcessOptions::force_ollama().force_ollama);
        assert!(ProcessOptions::force_ollama().force);
    }

    #[test]
    fn relative_to_config_strips_prefix() {
        let config = Path::new("/proj/llmcontext.yaml");
        let file = Path::new("/proj/src/main.rs");
        let rel = relative_to_config(config, file);
        assert_eq!(rel, "src/main.rs");
    }
}
